export const TYPES = {
  GET_GAMES: "GET_GAMES",
  GET_GAME_ID: "GET_GAME_ID",
  GET_GENRES: "GET_GENRES",
  FILTER_API_DB: "FILTER_API_DB",
  FILTER_GENRES: "FILTER_GENRES",
  ORDER_ALFABETIC: "ORDER_ALFABETIC",
};
